{{- $clusterName := required "Must set .Values.clusterName" .Values.clusterName }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-autoscaler.fullname" . }}
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "cluster-autoscaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
      labels:
        app: cluster-autoscaler
        {{- include "cluster-autoscaler.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cluster-autoscaler.serviceAccountName" . }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ssl-certs
          hostPath:
            path: {{ .Values.sslPath }}/{{ .Values.caBundle }}
        - name: nanny-config-volume
          configMap:
            name: {{ include "cluster-autoscaler.fullname" . }}-nanny-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - protocol: TCP
              containerPort: 8085
              name: metrics
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          command:
            - ./cluster-autoscaler

          args:
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/{{ $clusterName }}
            {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

        # https://aws.github.io/aws-eks-best-practices/cluster-autoscaling/#vertically-autoscaling-the-cluster-autoscaler
        - name: pod-nanny
          image: {{ .Values.podNanny.image.repository }}:{{ .Values.podNanny.image.tag }}
          imagePullPolicy: {{ .Values.podNanny.pullPolicy }}
          volumeMounts:
            - name: nanny-config-volume
              mountPath: /etc/config
          command:
            - /pod_nanny
          args:
            - --config-dir=/etc/config
            # Control the cluster-autoscaler deployment from the helm chart above...
            - --container={{ .Chart.Name }}
            - --deployment={{ include "cluster-autoscaler.fullname" . }}
            {{- with .Values.podNanny.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- with .Values.podNanny.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
