apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}-nanny
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  
- apiGroups:
  - apps
  resources:
  - deployments
  resourceNames:
  - {{ template "cluster-autoscaler.fullname" . }}
  verbs:
  - get
  - patch
