{{- /*
https://github.com/kubernetes-sigs/metrics-server/blob/v0.6.1/manifests/autoscale/rbac.yaml
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}-nanny
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
