{{- /*
https://raw.githubusercontent.com/kubernetes/autoscaler/cluster-autoscaler-1.24.0/charts/cluster-autoscaler/templates/role.yaml
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-autoscaler-status
      - cluster-autoscaler-priority-expander
    verbs:
      - delete
      - get
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-autoscaler
    verbs:
      - get
      - update
