{{- /*
Create a Service that can be used by the Prometheus ServiceMonitor to
monitor metrics from the node-local-dns-cache pods, as well as alert on them,
etc.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-local-dns.fullname" . }}
  namespace: {{ .Values.kubeDnsNamespace }}
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
  selector:
    {{- include "node-local-dns.selectorLabels" . | nindent 6 }}
